<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="Bogus" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Testcontainers" />
		<PackageReference Include="xunit" />
		<PackageReference Include="NetArchTest.Rules" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\src\API\Evently.Ticketing.Api\Evently.Ticketing.Api.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Ticketing\Evently.Modules.Ticketing.Application\Evently.Modules.Ticketing.Application.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Ticketing\Evently.Modules.Ticketing.Infrastructure\Evently.Modules.Ticketing.Infrastructure.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\compose\**" LinkBase="compose" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>