<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="NetArchTest.Rules" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\src\Modules\Users\Evently.Modules.Users.Application\Evently.Modules.Users.Application.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Users\Evently.Modules.Users.Domain\Evently.Modules.Users.Domain.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Users\Evently.Modules.Users.Infrastructure\Evently.Modules.Users.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Users\Evently.Modules.Users.IntegrationEvents\Evently.Modules.Users.IntegrationEvents.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Users\Evently.Modules.Users.Presentation\Evently.Modules.Users.Presentation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>