<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="Bogus" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Testcontainers" />
		<PackageReference Include="xunit" />
		<PackageReference Include="NetArchTest.Rules" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\API\Evently.Api\Evently.Api.csproj" />
	  <ProjectReference Include="..\..\src\API\Evently.Ticketing.Api\Evently.Ticketing.Api.csproj" Aliases="TicketingApi" />
	</ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\compose\**" LinkBase="compose" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\.files\realm-export.json" Link="compose\identity\realm-export.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>