<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\Evently.Shared.Application\Evently.Shared.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="MassTransit" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Quartz.Extensions.Hosting" />
		<PackageReference Include="Scrutor" />
	</ItemGroup>

</Project>
