<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="NetArchTest.Rules" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\src\Modules\Events\Evently.Modules.Events.Application\Evently.Modules.Events.Application.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Events\Evently.Modules.Events.Domain\Evently.Modules.Events.Domain.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Events\Evently.Modules.Events.Infrastructure\Evently.Modules.Events.Infrastructure.csproj" />
	  <ProjectReference Include="..\..\..\..\src\Modules\Events\Evently.Modules.Events.Presentation\Evently.Modules.Events.Presentation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>