<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Riok.Mapperly" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Scrutor" />
		<PackageReference Include="Serilog" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Evently.Shared.Domain\Evently.Shared.Domain.csproj" />
	</ItemGroup>
</Project>
