name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "r-[0-9]+.[0-9]+.[0-9]+"
      - "r-[0-9]+.[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNET_VERSION: "10.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Evently.slnx

      - name: Build
        run: dotnet build Evently.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Evently.slnx --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish Evently.slnx --configuration Release --no-restore --no-build
